spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTOCOMMIT=OFF;TRACE_LEVEL_SYSTEM_OUT=1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.hibernate.SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"